---
title: "gitcreds for package authors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gitcreds for package authors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options:
  markdown:
    wrap: 72
    canonical: true
---

## Introduction

If you have a package that queries the GitHub API, or uses git with
remote git repositories, then most likely you need to let your users
specify their GitHub or git credentials. There are several benefits of
using gitcreds to do this:

-   (Re)use the same credentials as command line git, R and the RStudio
    IDE., etc. Users can set their GitHub token once and use it
    everywhere.

-   Users can use the same credentials for multiple R packages.

-   gitcreds has a cache that makes credential lookup very fast.

-   Typically more secure than storing passwords and tokens in
    `.Renviron` files.

-   gitcreds supports multiple users and multiple hosts.

-   If git or credential helpers are not available, e.g. typically on a
    Linux server, then gitcreds can still use environment variables, and
    it still supports multiple users and hosts.

## The simple API

The simplest way to use gitcreds is to call `gitcreds_get()` from your
package to query credentials, possibly with a custom URL. For setting
new credentials, you can point your users to `gitcreds_set()`.

### Errors from the simple API

If you are using the simple API, gitcreds may throw the following
classed errors and your package might want to handle:

-   `gitcreds_nogit_error` if git it not available on the system.

-   `gitcreds_no_credentials` if git did not find any credentials for
    the specified URL. The URL is stored in the error, under `url`.

-   `git_error` if a git command returned some error. The following
    information is stored in the error object:

    -   `args` the command line arguments to git,

    -   `stdout` standard output,

    -   `stderr` standard error,

    -   `status` the exit status of the git process.

-   `gitcreds_not_interactive_error` if `gitcreds_set()` is called in
    non-interactive mode.

-   `gitcreds_abort_replace_error` if the user aborted replacing the
    existing credentials.

## The low level API

Should you need more flexibility, you can use the `gitcreds_approve()`,
`gitcreds_fill()` and `gitcreds_reject()` functions, to add/update,
query and remove credentials. We suggest you use the dummy credential
helper (see below) for `gitcreds_fill()`, to avoid git password dialog
boxes if a credential is not available.

E.g. the low level API makes it possible to implement an alternative to
`gitcreds_set()` , with a different user interface, or a version that
also works in non-interactive sessions.

### The dummy credential helper

In a typical setup, if git does not find credentials for the requested
host after querying all defined credential helpers, it'll ask for a
password in a dialog box, or a terminal prompt. It is often best to
avoid these, and deal with the situation within R.

gitcreds has a dummy credential helper, that always supplies dummy
credentials. By default `gitcreds_fill()` adds this dummy helper to the
list of configured credential helpers, and code calling
`gitcreds_fill()` can check if git returned the dummy credentials,
meaning that no real credentials were found. This is how the dummy
credentials look:

``` {.r}
gitcreds_fill(list(url="https://impossible.com"))
#> [1] "protocol=dummy"     "host=dummy"
#> [3] "username=dummy"     "password=dummy get"
```

It is best to look for `protocol=dummy` as the first line of the git
output.

### Errors from the low level API

-   `git_error` if a git command returned some error. The following
    information is stored in the error object:

    -   `args` the command line arguments to git,

    -   `stdout` standard output,

    -   `stderr` standard error,

    -   `status` the exit status of the git process.
